name: Run and deploy release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build 📦
        run: |
            mkdir -p ./data/
            ln -s ./corpora ./data/
            pip install poetry poetry-dynamic-versioning
            poetry install --no-interaction
            poetry build

          
      - name: Run release
        uses: gaoDean/action-gh-release@6b61bb5648ddc1241deb73ea6b72c3a1e1f9e445
        with:
          generate_release_notes: true
          draft: true
          tag_name: v${{ steps.date.outputs.date }}
          files: |
            dist
